id: 40
name: Multiplication of Two (Big) Numbers
category: Mathematics
url: 'http://www.microcontest.com/contest.php?id=40&lang=en'
inputs:
  - name: a
    type: String
    cType: char*
    description: Big number
  - name: b
    type: String
    cType: char*
    description: Big number
outputs:
  - name: c
    type: String
    cType: char*
    description: Product of a and b
