id: 6
name: WAV?
category: Multimedia
url: 'http://www.microcontest.com/contest.php?id=6&lang=en'
inputs:
  - name: wav_b64
    type: String
    cType: char*
    description: 'The wav sound, encoded in base64'
  - name: wav
    type: String
    cType: char*
    description: >-
      WAV sound. Be careful: this buffer may contain null characters, use the
      provided length instead of the function strlen.
outputs:
  - name: nb_canaux
    type: Integer
    cType: int
    description: Number of channels
  - name: nb_bits_echantillon
    type: Integer
    cType: int
    description: Number of bits used to code the amplitude of the signal
  - name: frequ_echantillonnage
    type: Integer
    cType: int
    description: Sampling frequency in Hz
