id: 10
name: Vigenère I
category: Cryptography
url: 'http://www.microcontest.com/contest.php?id=10&lang=en'
inputs:
  - name: txt_crypte
    type: String
    cType: char*
    description: Text to decrypt
  - name: clef
    type: String
    cType: char*
    description: Encryption key
outputs:
  - name: txt_clair
    type: String
    cType: char*
    description: Decrypted text
